spring.application.name=Inventory-Service
server.port = 8081


#Database configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Redis Configuration
spring.data.redis.host=localhost
spring.redis.port=6379


# Maximum size of a single uploaded file
spring.servlet.multipart.max-file-size=400MB

# Maximum size of complete multipart request
spring.servlet.multipart.max-request-size=450MB

# Write files larger than this threshold to disk instead of memory
spring.servlet.multipart.file-size-threshold=100MB

# Enable multipart upload
spring.servlet.multipart.enabled=true

logging.file.name=/app/log/application.log

jwt.secret.key = "my256bitsecretkeyfor256bitsecretkeydemo"

jwt.token.expiration.time = 360000


#actuator configurations
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true

# HTTP metrics
management.metrics.enable.http=true

# Include useful HTTP tags
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.95,0.99

# encryption key
security.token-encryption-key=mysecretekey123
